# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'nai', max_length=200)),
                ('image', models.FileField(blank=True, null=True, upload_to=b'')),
                ('type', models.CharField(blank=True, choices=[('1', 'picture'), ('2', 'logo'), ('3', 'poster'), ('4', 'videos')], default=b'Did Not Put', max_length=230, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('visibility_by_admin', models.BooleanField(default=True)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('license', models.CharField(blank=True, default=b'Did Not Put', max_length=230, null=True)),
                ('file_size', models.IntegerField(default=0)),
            ],
        ),
    ]
