# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='license',
            field=models.CharField(blank=True, default='Did Not Put', max_length=230, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(default='nai', max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'picture'), ('2', 'logo'), ('3', 'poster'), ('4', 'videos')], default='Did Not Put', max_length=230, null=True),
        ),
    ]
